### ISSUE TITLE
suspend_backoff wakelock cm-11-20140604-UNOFFICIAL-LegacyXperia-coconut

### ISSUE THREAD

**Issue by godlesplay** [LegacyXperia/local_manifests#643]
I lost more than 30% of battery through night, logs from betterbatterystats and your app, I was reading that it can be caused by google chrome but I'm not using it

![screenshot_2014-06-06-09-12-51](https://cloud.githubusercontent.com/assets/6266223/3197871/53512bee-ed50-11e3-9df1-6866bf8d33ab.png)
![screenshot_2014-06-06-09-13-00](https://cloud.githubusercontent.com/assets/6266223/3197872/5372d136-ed50-11e3-9d92-78c2162ac2b9.png)

http://www1.zippyshare.com/v/887348/file.html
http://www46.zippyshare.com/v/99571763/file.html

**Comment by azakosath** [comment]
I had the same wakelock last night and it kept my phone awake all night. The only thing I did was trying to make my laptop speakers play music from my coconut via bluetooth (without any luck). The partial wakelocks were normal, only that kernel wakelock was there, I rebooted without taking any logs.

**Comment by StrikerTwo** [comment]
See https://github.com/LegacyXperia/local_manifests/issues/15

**Comment by stefanverbeeck** [comment]
I am having the same kind of wakelock on my mango - BUT I have never even activated bluetooth on my device. (and i don't have chrome installed if that matters)

**Comment by godlesplay** [comment]
I'm not using bluetooth too...

**Comment by stefanverbeeck** [comment]
It seems to be gone for now when using ART - can you confirm this? - tested only an hour but the wakelock didn't show up yet.

**Comment by godlesplay** [comment]
today I didn't have this wakelock, now I'm charging phone, I will see later

**Comment by krikoCodeCook** [comment]
I had this last night too and couldn't stop it.
My battery was running out, so I didn't do much of research, but somehow deleting Google search app stopped it. NOTE: it might also be a placebo, had only 3% battery left, but the phone started entering deep sleep after that.

Haven't been using bluetooth or data connectivity. Just wifi.

**Comment by godlesplay** [comment]
I deleted google search app straight after flashing new build, I didn't use bluetooth or data connectivity too, but now everythings seems ok, maybe it was just single wakelock?

**Comment by krikoCodeCook** [comment]
Looking at explanation for this wakelock is really vague - it basically happens when "something" prevents the device from entering deep sleep in sequential short intervals. Then the phone decides to not enter deep sleep state for a longer period.

Please test more around google search. It might be the "hot word" detection causing this, since our phones don't support listening in standby mode (not sure on this one).

**Comment by krikoCodeCook** [comment]
It's not google search. Happened to me again.
I've disabled location, wifi, went into airplane mode and lastly disabled auto sync - nothing helped.

I don't remember this happening in 28.5 home build - deep sleep was working fine.

**Comment by godlesplay** [comment]
for me it is working fine now, I will write here with logs when I get this wakelock again

**Comment by krikoCodeCook** [comment]
I can't stop it anymore even with a reboot.
Full logs: https://drive.google.com/file/d/0B1ZKsglImPy3eTdSSkNfLV84bnM/edit?usp=sharing

I see this pattern:

```
<6>[ 4928.585081] lm3560 0-0053: lm356x_resume: Reinit lm356x chip.
<6>[ 4928.588194] lm3560 0-0053: lm356x_resume: Resuming LM356X driver.
<6>[ 4928.606413] PM: resume of devices complete after 249.107 msecs
<7>[ 4928.610655] Restarting tasks ... done.
<6>[ 4928.613127] PM: suspend exit 2014-06-07 12:21:43.015892197 UTC
<6>[ 4928.613402] suspend: exit suspend, ret = -11 (2014-06-07 12:21:43.016166728 UTC)
<6>[ 4928.613615] suspend: too many immediate wakeups, back off
<6>[ 4928.613768] active wake lock mmc1_detect
<6>[ 4928.613859] active wake lock suspend_backoff, time left 1000
<6>[ 4938.607878] PM: suspend entry 2014-06-07 12:21:53.009315427 UTC
```

lm356x could be the culprit?

**Comment by stefanverbeeck** [comment]
Did you try to actually remove velvet.apk in system/priv-app?
Now I don't have the wakelock anymore. I think my statement about enabling ART was wrong - the reason why is because I REMOVED velvet.apk in order to get some space in /data free as ART uses a lot of mb's.

**Comment by krikoCodeCook** [comment]
Velvet.apk? Never heard of it, neither of this workaround.
I'll restore the 4.6 build and test to see if it works. For last 2 hours it was stuck on lowest frequency - didn't enter deep sleep at all.

EDIT: I don't have velvet.apk on my phone.

**Comment by krikoCodeCook** [comment]
I went trough reinstalling older builds (28.5 vs 4.6) and testing with different kernels.
Wakelock magically disappeared now even on latest version (it didn't enter deep sleep anymore at all)

Disregard this
~~If someone is still suffering: reflash the same rom and boot - wait for the phone to settle and then monitor if it starts to deep sleep (e.g. cpu spy). Basically in standby mode the deep sleep should be the most used state - unless you have some exotic / weird apps.~~

EDIT: did any of you fiddle with cpu settings under performance?
I did, since I always overclock the cpu to 1.2Ghz. Removing the "Set on boot" tick and leaving it to stock (or just tick / untick, fiddle with frequency values and reflashed same rom), it enters deep sleep again (reboot was required).

I've repeated this test twice - with same results.

**Comment by neurer** [comment]
The suggested workaround (don't touch Performance settings) by krikoCodeCook works for me. Nice find. Thanks!

I'm on cm-11-20140604-UNOFFICIAL-LegacyXperia-smultron.

**Comment by godlesplay** [comment]
so problem is on changing freq and i/o side? I have default i/o and smartassv2 with min 122/max 1ghz

**Comment by krikoCodeCook** [comment]
More like frequencies, I never touch the I/O settings.
Either the settings app is somehow the culprit, or the kernel (default governor, when you mess with freq. probably?).
This could be tested by creating a startup script which alters frequencies instead of setting it via user interface.

For me deepsleep it's still working now, had a full charge in meantime.

**Comment by azakosath** [comment]
I was always on balanced profile when this wakelock started, so I don't think that it has something to do with changing the cpu frequencies.

**Comment by eldigo** [comment]
Manually clearing the Media Storage app data and reboot seems to have have solved the wakelock for me.. Someone else tried this as well?

**Comment by krikoCodeCook** [comment]
Again after a full charge, I left it and went to sleep.
Overnigh the battery seems it was draining like hell due to suspend_backoff and mmc1_detect.

Logs: https://drive.google.com/file/d/0B1ZKsglImPy3dGZyRFJETG5zUjA/edit?usp=sharing
Screenshot: https://drive.google.com/file/d/0B1ZKsglImPy3VmJwN0Nhb3A2MWs/edit?usp=sharing

I did a reboot and it disappeared - switching back and forth the "Set on boot" IO preference looked like it could be it, but sometimes it was behaving the same even with the checkbox enabled. It seemed to be random after a boot.

The same goes for clearing Media storage. Not sure what triggers this.

**Comment by enveraltin** [comment]
Do you have a lot of photos, Google+ and auto-backup enabled?

**Comment by krikoCodeCook** [comment]
In my case, none of the above.

**Comment by someuser1** [comment]
I had the same problem. Then in Privacy Guard I set keep awake to denied to all applications except Dialler and now I have no problems with the battery drain when i'm not using the phone. I use [20140604] version for coconut.

**Comment by eldigo** [comment]
issue solved in new build cm-11-20140620?

**Comment by rahonen** [comment]
Flashed 20140620 on my smultron and had this wakelock. I unticked "restore on boot" in the cpu settings, toggled bluetooth and wifi on/off, cleared Media Storage app data and rebooted. No wakelock anymore. Can't say which one of these did the trick or was is something else.

**Comment by krikoCodeCook** [comment]
Try next time fiddling with one by one and rebooting - it is time consuming, but I experience it more rarely and randomly.
For me till now seems more or less things point into "performance" settings being the culprit.
Or maybe more factors.

**Comment by lanmarc77** [comment]
Same problem here with 20140620. I uploaded the stats. It seems that without a SIM card it would never goto deep sleep. I tried a few times rebooting and all the tips above. Never got it to deep sleep.
http://pastebin.com/JP2LdGQz
http://pastebin.com/dJdD9q8b
http://pastebin.com/WYwWyrUS

Apart from this everything seems to work for me. 720p is good, wifi is stable, speed is awesome.
Keep up the good work.

**Comment by emaijala** [comment]
Problem still present for me too on iyokan 20140620 with default performance settings. I now have Link2SD installed, though. The wakelocks are there right after boot without having to do through any specific steps. Logs:

logcat: http://pastebin.com/NLXeJwbp
dmesg: http://pastebin.com/0HvVGggm
bbs: http://pastebin.com/cZR0ty3f

**Comment by godlesplay** [comment]
@lanmarc77 @emaijala try without gapps, I disabled few services with Disable Services app of google services framework and gms and now I haven't wakelocks

**Comment by Nikhildangui** [comment]
At times just turning on location services on and turning it off also keeps the device awake. 
Under battery gps shows off...  Its not due to gps always on buy. 
At time phone that is dealer keeps device awake.. Log attached for this...  And most of times Android os keeps it awake... Log attached...
![screenshot_2014-06-23-02-02-29](https://cloud.githubusercontent.com/assets/6098030/3352539/86595bc4-fa4d-11e3-999f-179d1e1a043d.png)

**Comment by Nikhildangui** [comment]
![screenshot_2014-06-12-18-46-45](https://cloud.githubusercontent.com/assets/6098030/3352542/abedfd54-fa4d-11e3-88b7-4b4a9ffa56e2.png)

**Comment by Nikhildangui** [comment]
Rename this jpg file as. Zip and extract for log
![bugreport](https://cloud.githubusercontent.com/assets/6098030/3352557/2552d00c-fa4e-11e3-8306-aa61a00fd354.jpg)

**Comment by enveraltin** [comment]
To all who suffer from this wakelock: I'd love if you could go to Settings->Privacy, enable privacy guard for Google Play Services (you'll need to enable "show system apps" from context menu), deny access to location, keep-awake and wake-up, test the drain and report. Your problem should go away, and if it does, it's very likely that this is a Google Play Services problem.

**Comment by lanmarc77** [comment]
@enveraltin @godlesplay  I do not have any google apps installed.
@mikeNG made a lot of changes recently. It is natural that things will not work right away but the only way to keep the devices uptodate. For me it is a miracle to have my Smultron run KK. As others pointed out at xda I would agree to provide logs so that mike gets a chance to fix it.

**Comment by enveraltin** [comment]
I totally agree. Main reason I'm here is that mango is the only device
available on the market that has a decent physical keyboard so I'm pretty
much stuck with this little beast until someone comes up with a stronger
device of similar size. Running kitkat on this thing is a miracle on its
own, a lot of us are grateful for all the effort @MikeNG has put in.

**Comment by xan1242** [comment]
I don't have a smultron (I'm on ayame/anzu), nor the latest nightly, but in my case it seems like the akmd sensor keeps wakelocking the device each time I put it to sleep. I already tried disabling the display rotation, however that doesn't help, nor does replacing the executable from an earlier build. I'm currently running a testbuild from 27/06.

http://puu.sh/9NZ9G/65f33ec360.zip

Notice that this is popping up each time the device is put to sleep:
"I/AKMD2   (  243): akmd2 : Suspended."

Also I am not sure if it's trying to draw something on the framebuffer:
"I/Choreographer(  855): Skipped 34 frames!  The application may be doing too much work on its main thread."

EDIT: Just found out on lines 3590 - 3595 (due to BBS request I assume)

"I/StatsAdapter( 3507): Values: "suspend_backoff"28 m 3 s  (1683 s)
I/StatsAdapter( 3507): Values: "PowerManagerService.WakeLocks"25 m 42 s  (1542 s)
I/StatsAdapter( 3507): Values: "mmc1_detect"28 m 3 s  (1683 s)
I/StatsAdapter( 3507): Values: "mmc0"28 m 3 s  (1683 s)
I/StatsAdapter( 3507): Values: "PowerManagerService.Broadcasts"25 m 42 s  (1542 s)
I/StatsAdapter( 3507): Values: "alarm"28 m 3 s  (1683 s)"

Could the alarm clock cause issues if the alarm sound is located on the SD card? I already know about mmc1_detect issues as well.

**Comment by lanmarc77** [comment]
Meanwhile I figured out that my smultron will not enter deep sleep at all unless it is powered off with bt off and powered on via offline charging. So there seems to be a difference booting cold to android and via offline charging mode. Hope this helps to pinpoint the error.

**Comment by xan1242** [comment]
Well, Ianmarc77 is right, same thing happens here. I guess we'll have to live with this trick for a little while until the bug is fixed.

Logs:
http://puu.sh/9OoJh/f35a03b871.zip

Notice how the messages related to the akmd sensor AND mmc1_detect are not there anymore. Obviously something related to those two is bugged. (I assume kernel)

**Comment by krikoCodeCook** [comment]
@lanmarc77 so practically deep sleep works for you well if you boot the phone by plugging in a charger, so I should turn it off and boot it off battery in order to start seeing wakelocks?

Interresting, since I mostly boot it via charger - when the battery completely drains.

**Comment by lanmarc77** [comment]
@krikoCodeCook Precisely.

**Comment by emaijala** [comment]
For the record, playing with Privacy Guard or Disable Services did not help, but the workaround of booting via offline charging works great for me too. Awesome battery life in that case. Maybe this helps find the difference between these boot methods causing the problem.

**Comment by Grof87** [comment]
Reposting my logs from the smultron thread I created (since it got locked)

https://gist.github.com/Grof87/985c649f59a6fa922ad3

**Comment by Grof87** [comment]
Logcat from the latest build 19.07.2014:
https://gist.github.com/Grof87/a6e8d548215a5423a846

**Comment by mikeNG** [comment]
rpcrotuer_smd_xprt seems to be the offending wakelock that triggers suspend_backoff.

I was able to reproduce this a lot of times in the past few days on my anzu. I'll try to find out what's happening.

**Comment by lanmarc77** [comment]
Looks like it comes from the rpc_read, which also seems to have a high wakeup count. Might be hard to find. Good luck I keep my fingers crossed...

**Comment by nussbaumer** [comment]
Its seems various functions/programs can trigger suspend_backoff. What would happen if you disable suspend_backoff function or set its trigger level way higher? Maybe its too easy to trigger, especially on our slow devices.

**Comment by dafuki** [comment]
I've been asked to describe my problem here (#754), so here's how I got the problem and how I fixed it.
after upgrading to cm-11-20140718-UNOFFICIAL-LegacyXperia-iyokan from cm-11-20140620-UNOFFICIAL-LegacyXperia-iyokan I started having a serious battery drain. Checking it shows a lot of `mmc1_detect`s, coming after `wl12xx` errors. Downgrading back to the previous version after a full wipe (system, factory, cache, etc) didn't fix the issue, after reading this thread and thinking a bit I guessed the issue was related to the SD card file system. So I formatted the SD card and now its working fine.
So my opinions (as a programmer myself) is that the wl driver error got the SD card corrupted because the system didn't do a proper "safe removal" of the SD card, which made the SD card's file system bad. This should be a change between 20140620(not included) and 20140718 for Iyokan. My two cents, Regards.
Update: seems like `mmc1_detect` is still present but with a much lower presence. Phone does go to deep sleep.

Another Update, the `storage` section of the settings shows as if the SD card is not loaded, but shows the files and I can access it.
Also now i'm seeing that `rpcrotuer_smd_xprt` (misspelled) is disturbing the suspend each time immediately, and that the `mmc1_detect` is launched after the sleep is already stopped by the RPC call. http://pastebin.com/E0XkbmNy could `mmc1_detect` not be the culprit? /me thinks there may be a problem with the SD card's loaded status flag or something

**Comment by erikwihlborg76** [comment]
A shot from the hip, can this edit 3 days ago MikeNG be related?

https://github.com/LegacyXperia/android_kernel_semc_msm7x30

**Comment by dafuki** [comment]
did the last commit fix this issue? i saw some commits about sdio

**Comment by BRAiNCHiLD95** [comment]
I could be very wrong, but on some googling about the _rpcrotuer_smd_xprt_, i found out that its misspelled...

Can someone, just for the heck of it, rename the rpcrotuer_smd_xprt file in their sources, and test it?

In the kernel source, exactly on this page : https://github.com/LegacyXperia/android_kernel_semc_msm7x30/tree/cm-11.0/arch/arm/mach-msm

There's a file called rpcrouter_smd_xprt.c
link to file: https://github.com/LegacyXperia/android_kernel_semc_msm7x30/blob/cm-11.0/arch/arm/mach-msm/rpcrouter_smd_xprt.c

I'd like to draw attention to line number 149, and 289.

149:    smd_remote_qdsp_xprt.xprt.name = "rpcrotuer_smd_qdsp_xprt";
289:         smd_remote_xprt.xprt.name = "rpcrotuer_smd_xprt";

both these lines have the misspelled code, i.e. 'rpcrotuer' instead of 'rpcrouter'..
 @mikeNG , @godlesplay , @krikoCodeCook  and every other dev here who builds from mike's sources -  have you tried checking this?
If possible, kindly try editing them to to the correct spelling code and try a build..
If this does solve the wakelock issue, everyone would be happy to get rid of one big headache.. :)
It's worth a try, right?

PS: I apologize if this had already been checked (i didn't see any post about it), and if it isn't a valid solution! :)

**Comment by godlesplay** [comment]
@BRAiNCHiLD95 thanks for it, but I'm not dev, and I can't build it myself, but if @mikeNG or someone other will build test build so I will test it

**Comment by Meninblack007** [comment]
See This https://github.com/LegacyXperia/local_manifests/issues/591
BTW I Was Building Rom For Haida.
If You Had Tell Me Then I Should Be Trying That In My Build..
But I Think it Will Fix It.

**Comment by MardonHH** [comment]
@BRAiNCHiLD95 
Thx for finding it.
Starting a new testbuild now ;)

https://github.com/LegacyXperia/android_kernel_semc_msm7x30/pull/4

**Comment by BRAiNCHiLD95** [comment]
@MardonHH :) hope to see a positive review aftr 24-48hrs! I hope we can kill that wakelock! :+1:

**Comment by Dilesh** [comment]
i will start a build now too. :) a PAC room :dancer:

**Comment by pcfighter** [comment]
it doesn't work

**Comment by MardonHH** [comment]
@pcfighter i thought so, its more a cosmetic change.
But anyway i think we should merge it in LX sources.

**Comment by pcfighter** [comment]
I'll suggest revert temporailly RPC changes to get deep sleep back, until Mike figure what's wrong in RPC code

**Comment by MardonHH** [comment]
@pcfighter which change was it?
Maybe we can run diff to find a hint whats causing the problem

**Comment by pcfighter** [comment]
commits with "RPC" in title ;)

**Comment by mikeNG** [comment]
We haven't made any changes that could cause this wakelock as far as I remember

**Comment by MardonHH** [comment]
rpcrouter_smd_xprt.c    Update copyright to The Linux Foundation    2 years ago
so the typo will stay even if we revert other rpc changes
@mikeNG 
only found  rpc_hsusb.c     Cleanup zeus ifdefs     2 months ago
semc_rpc_server_handset.c   Import semc_rpc_server_handset from 4.1.B.1.13  3 months ago

**Comment by pcfighter** [comment]
but if this config option will left disabled code won't be executed. Probably RPC code is not updated to upstream (according to repo from cherry-pick is)

in other words: We enabled config option with code causing wakelock. I suggest to disable it until we update the code.

**Comment by mikeNG** [comment]
If we disable RPC, bad things will happen. RPC is used to communicate with the device's modem

**Comment by pcfighter** [comment]
about RPC, i mean last 3 RPC commits :P 

Edit: Tested. Deep Sleep working now.

**Comment by MardonHH** [comment]
@pcfighter 
thats a good news :)

**Comment by pcfighter** [comment]
yup, but this randomly wakelocks could appear as before, now it is not all-time wakelock.

**Comment by dafuki** [comment]
What was the change which fixed this? the typo? the update to upstream?

**Comment by pcfighter** [comment]
edit; breaking: reverting rpc commits breaks BT. I hate dependencies.

**Comment by MardonHH** [comment]
too bad :(

**Comment by Dilesh** [comment]
with latest changes ( https://github.com/LegacyXperia/android_kernel_semc_msm7x30/commit/ba9867e5f9ff504cd08469e9539435a64e23dbf3) i get deep sleep . i checked after switch bt on and listen to some music with stereo bt headset and then turn it off. phone went to deep sleep. ( didnt reboot the phone)

ROM builders please check !!

[URL=http://www.imagebam.com/image/f13c2a348831019][IMG]http://thumbnails110.imagebam.com/34884/f13c2a348831019.jpg[/IMG][/URL]

**Comment by mikeNG** [comment]
Can someone try with the latest kernel changes I pushed?

**Comment by bjo81** [comment]
I'll try, but it will take some hours due to a new buildroot.

**Comment by MardonHH** [comment]
Ill start compiler for anzu in 2 hours when back at home.

**Comment by MardonHH** [comment]
suspend_backoff wakelock seems to be fixed now.

**Comment by MardonHH** [comment]
Still no more suspend_backoff wakelock.
@mikeNG 
I think you can close this bug now when new builds are started

**Comment by StrikerTwo** [comment]
Glad to see this finally seems to be resolved. Did I understand correctly that it was "only" a typo after all? 
Will there be builds for CM 10.2 or do I have to upgrade all "my" phones to CM 11?

**Comment by MardonHH** [comment]
No not the typo, thats only cosmetic change and should be done by CAF.
It is a different wakelock case (smd_rpcrouter)

Mike fixed (suspend_backoff wakelog) in another way.
